### ISSUE TITLE
能否支持一下英特尔的硬解，不用兼容模式？ 能整我就支持一下你- --===

### ISSUE THREAD

**Issue by homuraLan** [nyanmisaka/nyanmisaka#1]

**Comment by homuraLan** [comment]
我的cpu是8700k

**Comment by homuraLan** [comment]
只有在兼容模式下我才可以识别到我的核显

**Comment by nyanmisaka** [comment]
什么叫兼容模式？

**Comment by homuraLan** [comment]
我没记错的话 应该是叫VAAPI

**Comment by nyanmisaka** [comment]
VAAPI不是兼容模式，是QSV在Linux上的底层接口。
VAAPI就相当于Windows上的DXVA或D3D11VA硬件加速。

而且Jellyfin已经完全支持QSV，8700k也完全支持QSV。

**Comment by nyanmisaka** [comment]
如果有错误，请上传ffmpeg transcoding日志。

**Comment by homuraLan** [comment]
> 如果有错误，请上传ffmpeg transcoding日志。

`http://homura.top:5000/sharing/RFSxtAz9A`
QSV会有一些视频无法播放，提示不支持

**Comment by homuraLan** [comment]
> 如果有错误，请上传ffmpeg transcoding日志。

我知道了 错误的原因还是字幕导致的 我使用CSF下载字幕，并且给你的jellyfin加上了备用字库 但是都无法支持，会直接无法播放

**Comment by homuraLan** [comment]
> 如果有错误，请上传ffmpeg transcoding日志。

另外我取消备用字库也米有用，我是把Windows的字库全都拿来了

**Comment by nyanmisaka** [comment]
![image](https://user-images.githubusercontent.com/14953024/197335514-465213b0-7446-4eb2-9b8f-314314f2a28e.png)

**Comment by homuraLan** [comment]
> ![image](https://user-images.githubusercontent.com/14953024/197335514-465213b0-7446-4eb2-9b8f-314314f2a28e.png)

问题太多了 打算放弃了，入正emby，今天再看了一下又有别的原因 又和英文字幕有点关系，这个选项我已经关闭试过并重启过，jellyfin底层可能就有些屎山，后台能看到刚才打开的推流的视频还不能手动停止

**Comment by homuraLan** [comment]
> ![image](https://user-images.githubusercontent.com/14953024/197335514-465213b0-7446-4eb2-9b8f-314314f2a28e.png)

字幕一关秒播

**Comment by homuraLan** [comment]
我还特地打开字幕文件看了下是什么字体然后下载完拷贝进去还是没用 算了，

**Comment by homuraLan** [comment]
字幕的设置也弄了复杂格式字幕

**Comment by nyanmisaka** [comment]
跟字幕就没关系。按如图所示设置。

![屏幕截图 2022-10-22 213614](https://user-images.githubusercontent.com/14953024/197342058-1a909912-6e91-4b53-b185-53332cfa4d62.png)

**Comment by homuraLan** [comment]
> 跟字幕就没关系。按如图所示设置。
> 
> ![屏幕截图 2022-10-22 213614](https://user-images.githubusercontent.com/14953024/197342058-1a909912-6e91-4b53-b185-53332cfa4d62.png)

已测试无用，你说没关系，可是我就是关了字幕秒播

**Comment by homuraLan** [comment]
![image](https://user-images.githubusercontent.com/96775034/197344298-44b3a4d6-0e77-4947-8d9c-34ef83abffec.png)

**Comment by homuraLan** [comment]
![image](https://user-images.githubusercontent.com/96775034/197344437-d580fe4a-bfb2-41da-b42d-56145f2165b6.png)
给你全勾上了，然后关字幕秒播
![image](https://user-images.githubusercontent.com/96775034/197344475-55704653-b2f5-40ae-87a4-9a266e7287e9.png)
怎么样

**Comment by homuraLan** [comment]
![image](https://user-images.githubusercontent.com/96775034/197344761-c8bda930-ec8c-4394-b7c1-30371e5f481d.png)
我tm还重启一下容器，
照样秒播
![image](https://user-images.githubusercontent.com/96775034/197344801-d2d3765e-2f4f-4373-ab0c-2baa8eb29409.png)

**Comment by nyanmisaka** [comment]
1. 不能勾选"低电压模式"，因为不支持。

2. 最底下有"保存"按钮，我之前看日志保存的根本没生效
![image](https://user-images.githubusercontent.com/14953024/197344783-040f5545-4978-4e6f-ab7b-55fc9456e19c.png)

3. ASS字幕在我这一点问题没有
![屏幕截图 2022-10-22 223026](https://user-images.githubusercontent.com/14953024/197344837-4f615d32-56f8-4d95-a897-d7305fee0843.png)

**Comment by homuraLan** [comment]
![image](https://user-images.githubusercontent.com/96775034/197344928-769e2a53-02c7-4a29-a8e3-4720ef9f8df2.png)
那现在生效了 我刚重启的容器，而且我每次都有点保存 分享给你的时候应该只是开了而已 而且我也看到那个选项的提示了特意测试过

**Comment by homuraLan** [comment]
http://homura.top:5000/sharing/rtcTiOemT 新的日志

**Comment by nyanmisaka** [comment]
> [h264_qsv @ 0x55bc68866100] Error during encoding: device failed (-17)

你可能发现了一个bug。由intel驱动/内核或者ffmpeg引起，请提供内核版本号(uname -r)，我有时间在7代处理器上验证下。

> Stream #0:0(jpn): Video: h264 (High 10), yuv420p10le(tv, bt709, progressive), 1920x1080

另外就是，尽量把H.264 High 10的资源都换成HEVC Main 10的吧，没有显卡能硬解这个profile的。

**Comment by homuraLan** [comment]
还有一种可能 我之前安装过官版的 配置文件没有删除

**Comment by homuraLan** [comment]
> > [h264_qsv @ 0x55bc68866100] Error during encoding: device failed (-17)
> 
> 你可能发现了一个bug。由intel驱动/内核或者ffmpeg引起，请提供内核版本号(uname -r)，我有时间在7代处理器上验证下。
>
> > Stream #0:0(jpn): Video: h264 (High 10), yuv420p10le(tv, bt709, progressive), 1920x1080
> 
> 另外就是，尽量把H.264 High 10的资源都换成HEVC Main 10的吧，没有显卡能硬解这个profile的。

4.4.180+

**Comment by homuraLan** [comment]
顺便我想知道12代u兼容性如何

**Comment by nyanmisaka** [comment]
这个版本就是基于官版的，配置文件可以继承。

4.4.180+确实非常非常老了，应该是黑群之类的，你也可以用ubuntu 22.04 LTS试试会不会出现上面的-17错误。

12代需要5.19+内核。也是开箱即用，但黑裙就别想了。

我在评估Arc独显的性能。

![image](https://user-images.githubusercontent.com/14953024/197347010-cd271159-d1bd-4509-b82b-6e175e3fb041.png)

**Comment by homuraLan** [comment]
> 这个版本就是基于官版的，配置文件可以继承。
> 
> 4.4.180+确实非常非常老了，应该是黑群之类的，你也可以用ubuntu 22.04 LTS试试会不会出现上面的-17错误。
> 
> 12代需要5.19+内核。也是开箱即用，但黑裙就别想了。
> 
> 我在评估Arc独显的性能。
> 
> ![image](https://user-images.githubusercontent.com/14953024/197347010-cd271159-d1bd-4509-b82b-6e175e3fb041.png)

好吧 感谢回复，那感觉我可以洗洗睡了 我确实是群辉，但已经是最新的群辉了

**Comment by nyanmisaka** [comment]
> 4.4.180+确实非常非常老了，应该是黑群之类的，你也可以用ubuntu 22.04 LTS试试会不会出现上面的-17错误。

我这边验证了下，使用Ubuntu 20.04 LTS配合5.15的内核，一切正常。
所以这个问题应该是由内核版本太旧导致的QSV同步失败。
你可以尝试把核显直通给一台单独的机器。

**Comment by Sincejunly** [comment]
> 

我的核显就是直通的全功能跑在PVE上 硬解都是正常识别的

**Comment by homuraLan** [comment]
> 我的核显就是直通的全功能跑在PVE上 硬解都是正常识别的



> > 4.4.180+确实非常非常老了，应该是黑群之类的，你也可以用ubuntu 22.04 LTS试试会不会出现上面的-17错误。
> 
> 我这边验证了下，使用Ubuntu 20.04 LTS配合5.15的内核，一切正常。 所以这个问题应该是由内核版本太旧导致的QSV同步失败。 你可以尝试把核显直通给一台单独的机器。

我的核显就是直通的全功能跑在PVE上 硬解都是正常识别的

**Comment by nyanmisaka** [comment]
我的意思是直通给较新的内核版本的机器上。

**Comment by homuraLan** [comment]
> 我的意思是直通给较新的内核版本的机器上。

经测试emby正常播放

**Comment by nyanmisaka** [comment]
那你用emby吧，我也没办法了
